@extends('layouts.app')
@section('title',$account->exists?'Editar usuário':'Novo usuário')
@section('subtitle','Defina os dados e o perfil de acesso da pessoa.')
@section('content')<div class="card form-card"><div class="card-body p-4"><form action="{{ $account->exists?route('users.update',$account):route('users.store') }}" method="post">@csrf @if($account->exists) @method('PUT') @endif
<div class="row g-3"><div class="col-md-6"><label for="name" class="form-label">Nome</label><input class="form-control" id="name" name="name" value="{{ old('name',$account->name) }}" maxlength="160" required></div><div class="col-md-6"><label for="email" class="form-label">E-mail</label><input class="form-control" id="email" name="email" type="email" value="{{ old('email',$account->email) }}" maxlength="254" required></div>
<div class="col-md-6"><label for="role_id" class="form-label">Perfil de acesso</label><select class="form-select" id="role_id" name="role_id" required><option value="">Selecione um perfil</option>@foreach($roles as $role)<option value="{{ $role->id }}" @selected(old('role_id',$account->role_id)==$role->id)>{{ $role->name }}</option>@endforeach</select></div><div class="col-md-6"><label for="active" class="form-label">Situação</label><select class="form-select" id="active" name="active"><option value="1" @selected(old('active',$account->exists?$account->active:1)==1)>Ativo</option><option value="0" @selected(old('active',$account->exists?$account->active:1)==0)>Inativo</option></select></div>
<div class="col-md-6"><label for="password" class="form-label">{{ $account->exists?'Nova senha (opcional)':'Senha inicial' }}</label><input class="form-control" id="password" name="password" type="password" autocomplete="new-password" minlength="12" maxlength="72" @required(!$account->exists)><div class="form-text">Pelo menos 12 caracteres, incluindo letras e números.</div></div><div class="col-md-6"><label for="password_confirmation" class="form-label">Confirme a senha</label><input class="form-control" id="password_confirmation" name="password_confirmation" type="password" autocomplete="new-password" @required(!$account->exists)></div></div>
@if($account->exists)<p class="text-secondary small mt-3">Salvar encerra as sessões anteriores deste usuário. O proprietário não pode ser desativado por este formulário.</p>@endif
<div class="d-flex gap-2 mt-4"><button class="btn btn-primary">Salvar usuário</button><a href="{{ route('users.index') }}" class="btn btn-light">Cancelar</a></div></form></div></div>@endsection
