@extends('layouts.app')
@section('title','Documentos do paciente')
@section('subtitle',$patient->full_name)
@section('content')
<div class="d-flex gap-2 mb-4"><a class="btn btn-light" href="{{ route('patients.index') }}">Pacientes</a><a class="btn btn-outline-primary" href="{{ route('clinical.index',$patient) }}">Prontuário</a></div>
<div class="card mb-4"><div class="card-body p-4"><h2 class="h5">Adicionar documento</h2><form method="post" enctype="multipart/form-data" action="{{ route('documents.store',$patient) }}">@csrf
<label class="form-label" for="document">Arquivo PDF, JPEG ou PNG (até 10 MB)</label><input class="form-control mb-3" type="file" id="document" name="document" accept=".pdf,.jpg,.jpeg,.png" required>
<label class="form-label" for="category">Categoria</label><select class="form-select mb-3" id="category" name="category">@foreach(\App\Http\Controllers\DocumentController::CATEGORIES as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select>
<label class="form-label" for="appointment_id">Consulta vinculada (opcional)</label><select class="form-select mb-3" id="appointment_id" name="appointment_id"><option value="">Sem consulta vinculada</option>@foreach($appointments as $appointment)<option value="{{ $appointment->id }}">{{ $appointment->starts_at->setTimezone(\App\Support\Agenda::timezone())->format('d/m/Y H:i') }}</option>@endforeach</select><button class="btn btn-primary">Salvar documento privado</button></form></div></div>
<div class="card"><div class="card-body p-4"><h2 class="h5">Arquivos</h2>@forelse($documents as $document)<div class="border-top py-3"><p class="fw-semibold mb-1">{{ $document->name }}</p><p class="small text-secondary">{{ \App\Http\Controllers\DocumentController::CATEGORIES[$document->category] }} · {{ number_format($document->size_bytes/1024,1,',','.') }} KB · {{ $document->archived_at?'Arquivado':'Disponível' }}</p><div class="d-flex flex-wrap gap-2">@if(!$document->archived_at)<a class="btn btn-sm btn-outline-primary" href="{{ route('documents.download',[$patient,$document->id]) }}">Baixar documento</a>@endif<form method="post" action="{{ route('documents.archive',[$patient,$document->id]) }}">@csrf @method('PUT')<input type="hidden" name="lock_version" value="{{ $document->lock_version }}"><input type="hidden" name="archived" value="{{ $document->archived_at?0:1 }}"><button class="btn btn-sm btn-outline-secondary">{{ $document->archived_at?'Restaurar':'Arquivar' }}</button></form></div></div>@empty<p class="text-secondary">Nenhum documento enviado.</p>@endforelse{{ $documents->links() }}</div></div>
@endsection
