@extends('layouts.app')
@section('title','Integrações e lembretes')
@section('subtitle','Configure os canais e acompanhe o processamento das consultas.')
@section('content')
<div class="row g-4 mb-4">
<div class="col-lg-6"><div class="card h-100"><div class="card-body p-4"><h2 class="h5">Evolution API</h2>
<p class="text-secondary">Informe os dados de uma instância existente. O pareamento do WhatsApp é realizado no painel da Evolution.</p>
<form method="post" action="{{ route('integrations.credentials','evolution') }}">@csrf @method('PUT')
<input type="hidden" name="lock_version" value="{{ $settings->lock_version }}">
<label class="form-label" for="evolution_url">URL base HTTPS</label><input class="form-control mb-3" id="evolution_url" name="url" type="url" required maxlength="2048" placeholder="https://whatsapp.seudominio.com" value="{{ old('url',$credentials['evolution']['url']??'') }}">
<label class="form-label" for="evolution_instance">Nome da instância</label><input class="form-control mb-3" id="evolution_instance" name="instance" required maxlength="120" value="{{ old('instance',$credentials['evolution']['instance']??'') }}">
<label class="form-label" for="evolution_token">Chave da API</label><input class="form-control" id="evolution_token" name="token" type="password" autocomplete="new-password" maxlength="2048" @required(!$secrets['evolution'])>
<p class="form-text">{{ $secrets['evolution']?'Chave salva. Deixe em branco para mantê-la.':'Informe a chave fornecida pela Evolution API.' }}</p>
<button class="btn btn-primary">Salvar Evolution API</button></form>
<div class="border-top mt-3 pt-3">
@if(str_starts_with($credentials['evolution']['url']??'', 'https://'))
<a href="{{ rtrim($credentials['evolution']['url'],'/').'/manager' }}" target="_blank" rel="noopener noreferrer">Abrir painel da sua Evolution API ↗</a><br>
@endif
<a href="https://github.com/evolution-foundation/evolution-api#readme" target="_blank" rel="noopener noreferrer">Como configurar e obter as credenciais da Evolution API ↗</a>
<p class="form-text mb-0">A chave é definida na sua instalação (AUTHENTICATION_API_KEY) ou fornecida por quem hospeda a API. Não existe um portal único de emissão. Salve a URL base para abrir o painel da sua instalação por aqui.</p>
</div>
</div></div></div>
<div class="col-lg-6"><div class="card h-100"><div class="card-body p-4"><h2 class="h5">Configuração Google Calendar</h2>
<p class="text-secondary">No Google Cloud, habilite a Calendar API e crie um cliente OAuth do tipo Aplicativo da Web. Cadastre exatamente esta URL de redirecionamento:</p>
<div class="border rounded p-2 mb-3 text-break"><code>{{ route('integrations.google.callback') }}</code></div>
@if($connection)<p class="text-secondary">Desconecte a conta abaixo antes de alterar esta configuração.</p>@endif
<form method="post" action="{{ route('integrations.credentials','google') }}">@csrf @method('PUT')
<input type="hidden" name="lock_version" value="{{ $settings->lock_version }}">
<fieldset @disabled($connection)>
<label class="form-label" for="google_client_id">Client ID</label><input class="form-control mb-3" id="google_client_id" name="client_id" required maxlength="255" value="{{ old('client_id',$credentials['google']['client_id']??'') }}">
<label class="form-label" for="google_secret">Client Secret</label><input class="form-control" id="google_secret" name="client_secret" type="password" autocomplete="new-password" maxlength="2048" @required(!$secrets['google'])>
<p class="form-text">{{ $secrets['google']?'Segredo salvo. Deixe em branco para mantê-lo.':'Informe o segredo do cliente OAuth.' }}</p>
<label class="form-label" for="google_calendar">ID do calendário</label><input class="form-control" id="google_calendar" name="calendar_id" required maxlength="255" value="{{ old('calendar_id',$credentials['google']['calendar_id']??'') }}">
<p class="form-text">No Google Agenda: Configurações do calendário → Integrar agenda → ID da agenda. Use o ID explícito de uma agenda dedicada.</p>
<button class="btn btn-primary">Salvar configuração Google</button>
</fieldset></form>
<div class="border-top mt-3 pt-3"><a href="https://console.cloud.google.com/auth/clients" target="_blank" rel="noopener noreferrer">Criar credenciais OAuth no Google Cloud ↗</a>
<p class="form-text mb-0">Selecione seu projeto e crie um cliente do tipo Aplicativo da Web. <a href="https://developers.google.com/workspace/guides/create-credentials?hl=pt-br#web-application" target="_blank" rel="noopener noreferrer">Ver instruções oficiais ↗</a></p></div>
</div></div></div></div>

@php($labels=['pending'=>'Pendente','processing'=>'Envio em andamento','accepted'=>'Aceito pelo provedor','unknown'=>'Resultado incerto','failed'=>'Falhou','cancelled'=>'Cancelado','expired'=>'Prazo expirado','synced'=>'Sincronizado','retry'=>'Nova tentativa agendada','error'=>'Erro'])
<div class="card mb-4"><div class="card-body p-4"><h2 class="h5">Lembretes 24 horas antes</h2><p class="text-secondary">WhatsApp e e-mail usam o horário da consulta. O paciente deve autorizar cada canal em seu cadastro. Consultas marcadas com menos de 24 horas não geram envio imediato.</p><form method="post" action="{{ route('integrations.update') }}">@csrf @method('PUT')<input type="hidden" name="lock_version" value="{{ $settings->lock_version }}">
<div class="row g-3"><div class="col-md-4"><label for="whatsapp_provider" class="form-label">Provedor WhatsApp</label><select id="whatsapp_provider" name="whatsapp_provider" class="form-select"><option value="evolution" @selected($settings->whatsapp_provider==='evolution')>Evolution API</option><option value="meta" @selected($settings->whatsapp_provider==='meta')>Meta (oficial)</option></select></div><div class="col-md-4"><label for="whatsapp_enabled" class="form-label">WhatsApp</label><select class="form-select" id="whatsapp_enabled" name="whatsapp_enabled"><option value="0" @selected(!$settings->whatsapp_enabled)>Desativado</option><option value="1" @selected($settings->whatsapp_enabled)>Ativado</option></select></div><div class="col-md-4"><label for="email_enabled" class="form-label">E-mail</label><select class="form-select" id="email_enabled" name="email_enabled"><option value="0" @selected(!$settings->email_enabled)>Desativado</option><option value="1" @selected($settings->email_enabled)>Ativado</option></select></div></div><button class="btn btn-primary mt-3">Salvar canais</button></form>
<p class="small text-secondary mt-3 mb-0">Credenciais: Evolution {{ $ready['evolution']?'presente':'pendente' }} · Meta {{ $ready['meta']?'presente':'pendente' }} · SMTP {{ $ready['smtp']?'presente':'pendente' }}. Presença das credenciais não confirma conexão.</p></div></div>
<div class="card mb-4"><div class="card-body p-4"><h2 class="h5">Google Agenda</h2><p>Exportação do sistema para um calendário dedicado. Eventos usam o título "Consulta", sem nomes de pacientes, valores, convidados ou dados clínicos.</p>@if($connection)<p>Conectado ao calendário: {{ $connection->calendar_id }}</p><form method="post" action="{{ route('integrations.google.disconnect') }}">@csrf<button class="btn btn-outline-secondary">Desconectar</button></form>@else<p class="text-secondary">{{ $ready['google']?'Pronto para autorizar a conta Google.':'Preencha as credenciais Google e o identificador do calendário no formulário acima.' }}</p><form method="post" action="{{ route('integrations.google.connect') }}">@csrf<button class="btn btn-outline-primary" @disabled(!$ready['google'])>Conectar Google Agenda</button></form>@endif</div></div>
<p>Última execução do cron: {{ $settings->last_run_at?\Carbon\CarbonImmutable::parse($settings->last_run_at,'UTC')->setTimezone(\App\Support\Agenda::timezone())->format('d/m/Y H:i:s'):'Ainda não executado' }}.</p><p class="small text-secondary">O processamento ocorre a cada minuto. Lembretes atrasados mais de 5 minutos expiram. Aceito pelo provedor não significa entregue. Resultados incertos não são reenviados automaticamente. Alterações durante um envio já iniciado não podem recolher a mensagem.</p>
<div class="card mb-4"><div class="card-body p-4"><h2 class="h5">Lembretes recentes</h2><div class="table-responsive"><table class="table"><thead><tr><th>Consulta</th><th>Canal</th><th>Horário previsto</th><th>Situação</th><th>Detalhe</th></tr></thead><tbody>@forelse($reminders as $reminder)<tr><td>#{{ $reminder->appointment_id }} · v{{ $reminder->schedule_version }}</td><td>{{ $reminder->channel==='whatsapp'?'WhatsApp':'E-mail' }}</td><td>{{ \Carbon\CarbonImmutable::parse($reminder->scheduled_at,'UTC')->setTimezone(\App\Support\Agenda::timezone())->format('d/m/Y H:i') }}</td><td>{{ $labels[$reminder->status]??$reminder->status }}</td><td>{{ ['schedule_changed'=>'Consulta alterada','booked_after_target'=>'Agendada depois do prazo do lembrete','window_elapsed'=>'Janela de envio encerrada','patient_not_authorized'=>'Paciente inativo ou canal sem autorização','invalid_destination'=>'Contato inválido','provider_not_configured'=>'Provedor não configurado','transport_uncertain'=>'Sem confirmação do provedor','worker_interrupted'=>'Processamento interrompido'][$reminder->error_code] ?? ($reminder->error_code?'Resposta do provedor: '.$reminder->error_code:'—') }}</td></tr>@empty<tr><td colspan="5">Nenhum lembrete planejado.</td></tr>@endforelse</tbody></table></div>{{ $reminders->links() }}</div></div>
<div class="card"><div class="card-body p-4"><h2 class="h5">Últimas sincronizações Google</h2>@forelse($calendar as $event)<div class="border-top py-3">Consulta #{{ $event->appointment_id }} · {{ $labels[$event->status]??$event->status }} @if($event->error_code)<span class="text-secondary">({{ $event->error_code }})</span>@endif @if($connection && $event->connection_id===$connection->id && $event->status==='error')<form method="post" action="{{ route('integrations.google.retry',$event->id) }}">@csrf<button class="btn btn-sm btn-outline-primary">Tentar sincronizar novamente</button></form>@endif</div>@empty<p class="text-secondary">Nenhum evento sincronizado.</p>@endforelse</div></div>
@endsection
