@extends('layouts.app')
@section('title',$appointment->exists?'Reagendar consulta':'Nova consulta')
@section('subtitle','Escolha o paciente e o horário do atendimento.')
@section('content')<div class="card form-card"><div class="card-body p-4"><form method="post" action="{{ $appointment->exists?route('appointments.update',$appointment):route('appointments.store') }}">@csrf @if($appointment->exists) @method('PUT')<input type="hidden" name="lock_version" value="{{ $appointment->lock_version }}">@endif
<div class="row g-3">
@if(!$appointment->exists)<div class="col-12"><label for="service_type_id" class="form-label">Tipo de atendimento</label><select id="service_type_id" name="service_type_id" class="form-select" required><option value="">Selecione o atendimento</option>@foreach($serviceTypes as $type)<option value="{{ $type->id }}" @selected(old('service_type_id')==$type->id)>{{ $type->name }}</option>@endforeach</select>@if($serviceTypes->isEmpty())<p class="text-danger mt-2">O profissional precisa cadastrar um tipo de atendimento antes de agendar.</p>@endif</div>@else<div class="col-12"><p>Atendimento: {{ $appointment->service_name ?? 'Consulta anterior ao cadastro de tipos' }}</p></div>@endif
<div class="col-12"><label for="patient_id" class="form-label">Paciente</label><select class="form-select" id="patient_id" name="patient_id" required><option value="">Selecione um paciente</option>@foreach($patients as $patient)<option value="{{ $patient->id }}" @selected(old('patient_id',$appointment->patient_id)==$patient->id)>{{ $patient->full_name }}{{ $patient->active?'':' (inativo)' }}</option>@endforeach</select>@if($appointment->exists)<div class="form-text">O paciente é preservado no reagendamento. Para trocar, cancele e crie outra consulta.</div>@endif</div>
<div class="col-md-6"><label for="starts_at" class="form-label">Início</label><input class="form-control" id="starts_at" name="starts_at" type="datetime-local" value="{{ old('starts_at',$appointment->starts_at?->setTimezone($timezone)->format('Y-m-d\TH:i')) }}" required></div>
<div class="col-md-6"><label for="ends_at" class="form-label">Fim</label><input class="form-control" id="ends_at" name="ends_at" type="datetime-local" value="{{ old('ends_at',$appointment->ends_at?->setTimezone($timezone)->format('Y-m-d\TH:i')) }}" required></div>
<div class="col-md-6"><label for="modality" class="form-label">Modalidade</label><select class="form-select" id="modality" name="modality"><option value="in_person" @selected(old('modality',$appointment->modality)==='in_person')>Presencial</option><option value="online" @selected(old('modality',$appointment->modality)==='online')>On-line</option></select></div><div class="col-md-6"><label for="location" class="form-label">Local (opcional)</label><input class="form-control" id="location" name="location" maxlength="255" value="{{ old('location',$appointment->location) }}"></div>
@if($appointment->exists)<div class="col-12"><label class="form-label" for="reason">Motivo do reagendamento (opcional)</label><input class="form-control" name="reason" id="reason" maxlength="255" value="{{ old('reason') }}"></div>@endif
@if($appointment->status==='waiting')<div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="confirm_waiting" id="confirm_waiting" value="1" required><label class="form-check-label" for="confirm_waiting">Confirmo a retirada do paciente da fila de espera para reagendar.</label></div></div>@endif
</div><p class="text-secondary small mt-3">Horários no fuso {{ $timezone }}. Não inclua informações clínicas nos campos de agenda.</p><div class="d-flex gap-2 mt-4"><button class="btn btn-primary">{{ $appointment->exists?'Salvar reagendamento':'Agendar consulta' }}</button><a class="btn btn-light" href="{{ route('appointments.index') }}">Cancelar</a></div></form></div></div>@endsection
