@extends('layouts.app')
@section('title',$patient->exists?'Editar paciente':'Novo paciente')
@section('subtitle','Dados administrativos. As anotações clínicas terão um espaço exclusivo do profissional.')
@section('content')
<div class="card form-card"><div class="card-body p-4"><form method="post" action="{{ $patient->exists?route('patients.update',$patient):route('patients.store') }}">@csrf
@if($patient->exists) @method('PUT')<input type="hidden" name="lock_version" value="{{ $patient->lock_version }}">@endif
<div class="row g-3">
<div class="col-md-8"><label class="form-label" for="full_name">Nome completo</label><input class="form-control" id="full_name" name="full_name" value="{{ old('full_name',$patient->full_name) }}" maxlength="160" required></div>
<div class="col-md-4"><label class="form-label" for="birth_date">Data de nascimento</label><input class="form-control" id="birth_date" name="birth_date" type="date" value="{{ old('birth_date',$patient->birth_date?->format('Y-m-d')) }}" max="{{ now()->format('Y-m-d') }}"></div>
<div class="col-md-6"><label class="form-label" for="phone">Telefone</label><input class="form-control" id="phone" name="phone" type="tel" value="{{ old('phone',$patient->phone) }}" maxlength="25"></div>
<div class="col-md-6"><label class="form-label" for="email">E-mail</label><input class="form-control" id="email" name="email" type="email" value="{{ old('email',$patient->email) }}" maxlength="254"></div>
<div class="col-md-6"><label class="form-label" for="guardian_name">Nome do responsável (opcional)</label><input class="form-control" id="guardian_name" name="guardian_name" value="{{ old('guardian_name',$patient->guardian_name) }}" maxlength="160"></div>
<div class="col-md-6"><label class="form-label" for="guardian_phone">Telefone do responsável</label><input class="form-control" id="guardian_phone" name="guardian_phone" type="tel" value="{{ old('guardian_phone',$patient->guardian_phone) }}" maxlength="25"></div>
<div class="col-12"><fieldset class="border rounded p-3"><legend class="float-none w-auto fs-6 px-2">Autorização de lembretes</legend><input type="hidden" name="whatsapp_reminders" value="0"><input type="hidden" name="email_reminders" value="0"><div class="form-check"><input class="form-check-input" type="checkbox" name="whatsapp_reminders" id="whatsapp_reminders" value="1" @checked(old('whatsapp_reminders',$patient->whatsapp_reminders))><label class="form-check-label" for="whatsapp_reminders">Paciente autorizou lembretes por WhatsApp</label></div><div class="form-check"><input class="form-check-input" type="checkbox" name="email_reminders" id="email_reminders" value="1" @checked(old('email_reminders',$patient->email_reminders))><label class="form-check-label" for="email_reminders">Paciente autorizou lembretes por e-mail</label></div><label for="communication_source" class="form-label mt-3">Como a autorização foi obtida</label><input class="form-control" id="communication_source" name="communication_source" maxlength="160" value="{{ old('communication_source',$patient->communication_source) }}"><p class="small text-secondary mt-2 mb-0">Para WhatsApp, use telefone internacional: +5511999999999. Os canais dependem da ativação pelo profissional.</p></fieldset></div>
<div class="col-md-6"><label class="form-label" for="active">Situação</label><select class="form-select" id="active" name="active"><option value="1" @selected(old('active',$patient->active)==1)>Ativo</option><option value="0" @selected(old('active',$patient->active)==0)>Inativo</option></select><div class="form-text">Inativar impede novos agendamentos e preserva o histórico.</div></div>
</div><div class="d-flex gap-2 mt-4"><button class="btn btn-primary">Salvar cadastro</button><a class="btn btn-light" href="{{ route('patients.index') }}">Cancelar</a></div>
</form></div></div>
@endsection
