@extends('layouts.app')
@section('title','Cobrança da consulta')
@section('subtitle',$charge->appointment->patient->full_name)
@section('content')
@php($balance=$charge->balanceCents())
<div class="card mb-4"><div class="card-body p-4"><h2 class="h5">{{ $charge->appointment->service_name ?? 'Consulta anterior ao cadastro de tipos' }}</h2><p>{{ $charge->appointment->starts_at->setTimezone(\App\Support\Agenda::timezone())->format('d/m/Y H:i') }} · {{ $charge->appointment->statusLabel() }}</p><p class="mb-1">Valor: <strong>{{ $charge->amount===null?'A definir pelo profissional':\App\Support\Money::display(\App\Support\Money::cents($charge->amount)) }}</strong></p><p class="mb-1">Saldo: <strong>{{ $balance===null?'—':\App\Support\Money::display($balance) }}</strong></p><p class="mb-0">{{ $charge->label() }}</p></div></div>
@if($charge->status==='open' && $balance>0)<div class="card mb-4"><div class="card-body p-4"><h2 class="h5">Registrar recebimento</h2><form method="post" action="{{ route('billing.receive',$charge) }}">@csrf<input type="hidden" name="lock_version" value="{{ $charge->lock_version }}"><input type="hidden" name="idempotency_key" value="{{ old('idempotency_key', (string) \Illuminate\Support\Str::uuid()) }}"><div class="row g-3"><div class="col-md-6"><label class="form-label" for="payment-amount">Valor recebido (R$)</label><input class="form-control" id="payment-amount" name="amount" value="{{ old('amount',\App\Support\Money::decimal($balance)) }}" inputmode="decimal" required></div><div class="col-md-6"><label class="form-label" for="method">Forma de pagamento</label><select class="form-select" name="method" id="method">@foreach(\App\Support\Billing::METHODS as $key=>$label)<option value="{{ $key }}" @selected(old('method')===$key)>{{ $label }}</option>@endforeach</select></div></div><p class="small text-secondary mt-3">Registre somente valores já recebidos. Este lançamento não realiza transferências nem cobra o paciente automaticamente.</p><button class="btn btn-primary">Registrar pagamento recebido</button></form></div></div>@endif
@if($owner)
<div class="card mb-4"><div class="card-body p-4"><h2 class="h5">Ajustar cobrança</h2><form method="post" action="{{ route('finance.adjust',$charge) }}">@csrf @method('PUT')<input type="hidden" name="lock_version" value="{{ $charge->lock_version }}"><div class="row g-3"><div class="col-md-4"><label for="charge-amount" class="form-label">Valor acordado (R$)</label><input id="charge-amount" class="form-control" name="amount" value="{{ $charge->amount }}" inputmode="decimal" required></div><div class="col-md-4"><label for="charge-status" class="form-label">Situação</label><select class="form-select" id="charge-status" name="status">@foreach(['open'=>'Aberta','waived'=>'Dispensada','void'=>'Anulada'] as $key=>$label)<option value="{{ $key }}" @selected($charge->status===$key)>{{ $label }}</option>@endforeach</select></div><div class="col-md-4"><label for="reason" class="form-label">Motivo</label><input class="form-control" id="reason" name="reason" maxlength="255" required></div></div><button class="btn btn-outline-primary mt-3">Salvar ajuste</button></form></div></div>
<div class="card mb-4"><div class="card-body p-4"><h2 class="h5">Recebimentos e estornos</h2>@forelse($payments as $payment)<div class="border-top py-3"><p>{{ \App\Support\Money::display(\App\Support\Money::cents((string)$payment->amount)) }} · {{ \App\Support\Billing::METHODS[$payment->method] }} · {{ \Carbon\CarbonImmutable::parse($payment->received_at,'UTC')->setTimezone(\App\Support\Agenda::timezone())->format('d/m/Y H:i') }}</p>@if($payment->reversal_id)<p class="text-secondary">Estornado: {{ $payment->reversal_reason }}</p>@else<form method="post" action="{{ route('finance.reverse',[$charge,$payment->id]) }}" data-confirm="Registrar o estorno integral deste recebimento?">@csrf<label class="form-label" for="reason-{{ $payment->id }}">Motivo do estorno integral</label><input class="form-control mb-2" id="reason-{{ $payment->id }}" name="reason" maxlength="255" required><button class="btn btn-outline-danger btn-sm">Registrar estorno</button></form>@endif</div>@empty<p class="text-secondary">Nenhum recebimento registrado.</p>@endforelse<p class="small text-secondary mb-0">O estorno registra a correção no sistema. Eventual devolução deve ser feita pelo profissional no meio de pagamento.</p></div></div>
<div class="card mb-4"><div class="card-body p-4"><h2 class="h5">Histórico da cobrança</h2>@foreach($history as $event)<p class="small mb-2">{{ \Carbon\CarbonImmutable::parse($event->created_at,'UTC')->setTimezone(\App\Support\Agenda::timezone())->format('d/m/Y H:i') }} · {{ ['created'=>'Cobrança criada','rescheduled'=>'Vencimento atualizado','adjusted'=>'Cobrança ajustada'][$event->action] ?? $event->action }} @if($event->reason) · {{ $event->reason }} @endif</p>@endforeach</div></div>
@endif
<a href="{{ $owner?route('finance.index'):route('billing.today') }}" class="btn btn-light mb-4">Voltar</a>
@endsection
