<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>@yield('title','Painel') · Medpsico</title><link rel="stylesheet" href="{{ asset('vendor/adminlte/adminlte.min.css') }}"><link rel="stylesheet" href="{{ asset('css/app.css') }}"></head>
<body class="layout-fixed sidebar-expand-lg bg-body-tertiary"><div class="app-wrapper">
<header class="app-header navbar navbar-expand bg-white border-bottom"><div class="container-fluid"><button type="button" class="btn btn-light me-3" data-lte-toggle="sidebar" aria-label="Abrir ou fechar menu">☰</button><span class="text-secondary small">Consultório de psicologia</span><div class="ms-auto d-flex align-items-center gap-3"><span class="small d-none d-sm-inline">{{ auth()->user()->name }}</span><form action="{{ route('logout') }}" method="post">@csrf<button class="btn btn-outline-secondary btn-sm">Sair</button></form></div></div></header>
<aside class="app-sidebar shadow" data-bs-theme="dark"><div class="sidebar-brand"><a href="{{ route('dashboard') }}" class="brand-link"><span class="brand-mark">m</span><span class="brand-text fw-light">med<strong>psico</strong></span></a></div><div class="sidebar-wrapper"><div class="sidebar-caption">CONSULTÓRIO</div><nav aria-label="Navegação principal"><ul class="nav sidebar-menu flex-column" data-lte-toggle="treeview"><li class="nav-item"><a href="{{ route('dashboard') }}" class="nav-link {{ request()->routeIs('dashboard')?'active':'' }}"><span class="nav-icon">◷</span><p>Painel</p></a></li>
@can('patients.manage')<li class="nav-item"><a href="{{ route('patients.index') }}" class="nav-link {{ request()->routeIs('patients.*')?'active':'' }}"><span class="nav-icon">♙</span><p>Pacientes</p></a></li>@endcan
@if(\App\Support\Agenda::mayView(auth()->user()))<li class="nav-item"><a href="{{ route('appointments.index') }}" class="nav-link {{ request()->routeIs('appointments.*')?'active':'' }}"><span class="nav-icon">▦</span><p>Agenda</p></a></li>@endif
@can('billing.today')<li class="nav-item"><a href="{{ route('billing.today') }}" class="nav-link {{ request()->routeIs('billing.*')?'active':'' }}"><span class="nav-icon">$</span><p>Cobranças do dia</p></a></li>@endcan
@can('finance.manage')<li class="nav-item"><a href="{{ route('finance.index') }}" class="nav-link {{ request()->routeIs('finance.index')?'active':'' }}"><span class="nav-icon">$</span><p>Financeiro</p></a></li><li class="nav-item"><a href="{{ route('finance.types') }}" class="nav-link {{ request()->routeIs('finance.types*')?'active':'' }}"><span class="nav-icon">≡</span><p>Tipos de atendimento</p></a></li>@endcan
@can('integrations.manage')<li class="nav-item"><a href="{{ route('integrations.index') }}" class="nav-link {{ request()->routeIs('integrations.*')?'active':'' }}"><span class="nav-icon">⇄</span><p>Integrações</p></a></li>@endcan
@can('users.manage')<li class="nav-header">ADMINISTRAÇÃO</li><li class="nav-item"><a href="{{ route('users.index') }}" class="nav-link {{ request()->routeIs('users.*')?'active':'' }}"><span class="nav-icon">♙</span><p>Usuários</p></a></li><li class="nav-item"><a href="{{ route('roles.index') }}" class="nav-link {{ request()->routeIs('roles.*')?'active':'' }}"><span class="nav-icon">▤</span><p>Perfis de acesso</p></a></li>@endcan
</ul></nav><div class="sidebar-note">{{ auth()->user()->isOwner()?'Psicólogo responsável':auth()->user()->role->name }}</div></div></aside>
<main class="app-main"><div class="app-content-header"><div class="container-fluid"><p class="eyebrow mb-2">@yield('eyebrow','SEU CONSULTÓRIO')</p><h1 class="h3 fw-semibold">@yield('title','Painel')</h1><p class="text-secondary mb-0">@yield('subtitle')</p></div></div><div class="app-content"><div class="container-fluid">@include('partials.feedback') @yield('content')</div></div></main>
<footer class="app-footer small"><strong>Medpsico</strong><span class="float-end text-secondary">Gestão do consultório</span></footer></div><script src="{{ asset('vendor/bootstrap/bootstrap.bundle.min.js') }}" defer></script><script src="{{ asset('vendor/adminlte/adminlte.min.js') }}" defer></script><script src="{{ asset('js/agenda.js') }}" defer></script></body></html>
